name: make windows package

on:
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build-love:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build love file
        uses: love-actions/love-actions-core@v1
        with:
          build-list: "./src/*"
          package-path: "./game.love"

      - name: upload love file
        uses: actions/upload-artifact@v4
        with:
          name: "love-file"
          path: "./game.love"

  build-windows-package:
    runs-on: windows-latest
    needs: build-love
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: "love-file"
          path: "./"

      - name: build windows package
        uses: love-actions/love-actions-windows@v2
        with:
          love-package: "./game.love"
          product-name: "arcturin"

      - name: upload windows package
        uses: actions/upload-artifact@v4
        with:
          name: "arcturin-windows"
          path: "./build/arcturin_x64.zip"

  create-release:
    runs-on: ubuntu-latest
    needs: build-windows-package
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: "arcturin-windows"
          path: "./"

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: "arcturin_x64.zip"
          tag_name: ${{ github.run_id }}
          name: "release ${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
