name: Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-love:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build love file
        uses: love-actions/love-actions-core@v1
        with:
          build-list: "./src/*"
          package-path: "./game.love"

      - name: upload love file
        uses: actions/upload-artifact@v4
        with:
          name: "game-love-file"
          path: "./game.love"

      - name: build windows package
        uses: love-actions/love-actions-windows@v2
        with:
          love-package: "./game.love"
          # icon-path:
          product-name: "arcturin"

      - name: upload windows package
        uses: actions/upload-artifact@v4
        with:
          name: "game-windows-package"
          path: "./build/*"
